// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojfcsrsjthzoqckahrwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qZmNzcnNqdGh6b3Fja2FocndyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDIyMzcsImV4cCI6MjA2NzMxODIzN30.Lh5KWpNCgtfzNlfgP6b2fC6DrNvjRzqWIt8vfOZfp2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});